"""add code and sub-category target to promos

Revision ID: 275a4626eae4
Revises: 7efc515e5ec9
Create Date: 2026-09-26 01:55:31.557688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275a4626eae4'
down_revision: Union[str, None] = '7efc515e5ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promos', sa.Column('code', sa.String(), nullable=True))
    op.add_column('promos', sa.Column('target_sub_category_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'promos', ['code'])
    op.create_foreign_key(None, 'promos', 'sub_categories', ['target_sub_category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promos', type_='foreignkey')
    op.drop_constraint(None, 'promos', type_='unique')
    op.drop_column('promos', 'target_sub_category_id')
    op.drop_column('promos', 'code')
    # ### end Alembic commands ###
