"""add promotions and guest visits

Revision ID: 45b8d0e3608d
Revises: 0ad8fc047ac8
Create Date: 2026-09-22 22:32:41.242783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45b8d0e3608d'
down_revision: Union[str, None] = '0ad8fc047ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.String(), nullable=False),
    sa.Column('visit_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'guest_id', name='uq_guest_visit')
    )
    op.create_table('promotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(), server_default='notice', nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('kicker', sa.String(), nullable=True),
    sa.Column('dek', sa.String(), nullable=True),
    sa.Column('cta', sa.String(), server_default='book', nullable=False),
    sa.Column('cta_label', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('offer', sa.String(), server_default='none', nullable=False),
    sa.Column('off', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starts_at', sa.Date(), nullable=False),
    sa.Column('ends_at', sa.Date(), nullable=True),
    sa.Column('is_on', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('who', sa.String(), server_default='all', nullable=False),
    sa.Column('quiet_days', sa.Integer(), server_default='50', nullable=False),
    sa.Column('regular_visits', sa.Integer(), server_default='4', nullable=False),
    sa.Column('surfaces', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('look', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('map_id', sa.String(), nullable=True),
    sa.Column('created_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions')
    op.drop_table('guest_visits')
    # ### end Alembic commands ###
