"""edit the menu_item table and add order_items table

Revision ID: 467b0135f8e8
Revises: c07121ac0baf
Create Date: 2026-07-29 14:35:56.330269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '467b0135f8e8'
down_revision: Union[str, None] = 'c07121ac0baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('menu_items', sa.Column('dietary_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('menu_items', sa.Column('allergen_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'allergen_tags')
    op.drop_column('menu_items', 'dietary_tags')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
