"""add relationship of main-category to tenant model

Revision ID: 57748532dd04
Revises: e8e86d36c6c2
Create Date: 2026-07-29 11:27:08.515152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57748532dd04'
down_revision: Union[str, None] = 'e8e86d36c6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
