"""add pictures list to menu items

Revision ID: 66faa6fd9f34
Revises: 45b8d0e3608d
Create Date: 2026-09-22 23:45:20.162082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66faa6fd9f34'
down_revision: Union[str, None] = '45b8d0e3608d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('pictures', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'pictures')
    # ### end Alembic commands ###
