"""add order placed_by_staff_id

Revision ID: 6d2cc4add89e
Revises: a77ca726a0c7
Create Date: 2026-08-11 06:21:19.680178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2cc4add89e'
down_revision: Union[str, None] = 'a77ca726a0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('placed_by_staff_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'staff', ['placed_by_staff_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'placed_by_staff_id')
    # ### end Alembic commands ###
