"""Add the created at column in Order item 

Revision ID: 7818677ac94f
Revises: 6d2cc4add89e
Create Date: 2026-08-11 12:33:45.253216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7818677ac94f'
down_revision: Union[str, None] = '6d2cc4add89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'created_at')
    # ### end Alembic commands ###
