"""add prep_station, order item status, ready order status

Revision ID: 7c28a99a986c
Revises: f47ff88c8490
Create Date: 2026-08-17 14:00:41.786573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c28a99a986c'
down_revision: Union[str, None] = 'f47ff88c8490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("COMMIT")
    op.execute("ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'ready' AFTER 'in_progress'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_categories', sa.Column('prep_station', sa.String(), server_default='kitchen', nullable=False))
    op.add_column('order_items', sa.Column('status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'status')
    op.drop_column('main_categories', 'prep_station')
    # ### end Alembic commands ###
