"""add promo_code to orders

Revision ID: 7efc515e5ec9
Revises: 66faa6fd9f34
Create Date: 2026-09-25 23:57:24.276682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7efc515e5ec9'
down_revision: Union[str, None] = '66faa6fd9f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('promo_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'promo_code')
    # ### end Alembic commands ###
