"""update the relationship between staff and role tables

Revision ID: 8d41ea903b36
Revises: 13481a0ec3dc
Create Date: 2026-08-04 23:59:53.249377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d41ea903b36'
down_revision: Union[str, None] = '13481a0ec3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
