"""add layout and ctas to events

Revision ID: 9985f1b58458
Revises: 9cc7c9b0cd18
Create Date: 2026-09-20 02:31:33.632490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9985f1b58458'
down_revision: Union[str, None] = '9cc7c9b0cd18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('events', sa.Column('ctas', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'ctas')
    op.drop_column('events', 'layout')
    # ### end Alembic commands ###
