"""add the image url column to branch model

Revision ID: a66437e593e3
Revises: 8d41ea903b36
Create Date: 2026-08-07 02:02:24.319634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66437e593e3'
down_revision: Union[str, None] = '8d41ea903b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'image_url')
    # ### end Alembic commands ###
