"""Update the staff details in the staff model

Revision ID: a77ca726a0c7
Revises: a66437e593e3
Create Date: 2026-08-10 15:45:13.779043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77ca726a0c7'
down_revision: Union[str, None] = 'a66437e593e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('picture_url', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('staff', sa.Column('address', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('national_insurance_number', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('right_to_work_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('staff', sa.Column('shift_pattern', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('staff', sa.Column('pay_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'pay_type')
    op.drop_column('staff', 'salary')
    op.drop_column('staff', 'notes')
    op.drop_column('staff', 'shift_pattern')
    op.drop_column('staff', 'right_to_work_verified')
    op.drop_column('staff', 'national_insurance_number')
    op.drop_column('staff', 'employment_type')
    op.drop_column('staff', 'emergency_contact_phone')
    op.drop_column('staff', 'emergency_contact_name')
    op.drop_column('staff', 'address')
    op.drop_column('staff', 'date_of_birth')
    op.drop_column('staff', 'picture_url')
    # ### end Alembic commands ###
