"""rework promos for targeted discounts

Revision ID: c507e7a9645a
Revises: 6ddfc6134769
Create Date: 2026-08-22 22:55:38.663139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c507e7a9645a'
down_revision: Union[str, None] = '6ddfc6134769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promos', sa.Column('target_type', sa.String(), server_default='item', nullable=False))
    op.add_column('promos', sa.Column('target_menu_item_id', sa.UUID(), nullable=True))
    op.add_column('promos', sa.Column('target_main_category_id', sa.UUID(), nullable=True))
    op.add_column('promos', sa.Column('discount_type', sa.String(), server_default='percentage', nullable=False))
    op.add_column('promos', sa.Column('fixed_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'promos', 'menu_items', ['target_menu_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promos', 'main_categories', ['target_main_category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promos', type_='foreignkey')
    op.drop_constraint(None, 'promos', type_='foreignkey')
    op.drop_column('promos', 'fixed_price')
    op.drop_column('promos', 'discount_type')
    op.drop_column('promos', 'target_main_category_id')
    op.drop_column('promos', 'target_menu_item_id')
    op.drop_column('promos', 'target_type')
    # ### end Alembic commands ###
